export const USER_SEND_REQUEST = 'USER_SEND_REQUEST'
export const USER_GET_REQUEST = 'USER_GET_REQUEST'
export const GET_ERROR = 'GET_ERROR'

export const ADD_ITEM = 'ADD_ITEM'
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS'
export const DELETE_ITEM = 'DELETE_ITEM'

export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST"
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT"
export const ADD_NEW_PRODUCT_ERROR = "ADD_NEW_PRODUCT_ERROR"

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'


